name: Wikipedia Importer CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  parser_and_search:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: docker build -t wikipedia-importer .

    - name: Initialize Database
      run: docker run wikipedia-importer python scripts/starter.py

    - name: Start Wikipedia Parser
      run: docker run wikipedia-importer python scripts/wiki_parser.py data/example_wikipedia-articles.xml

    - name: Sleep to ensure parser completion
      run: sleep 10  # sleep for 10 seconds

    - name: Run Wiki Searcher
      run: docker run wikipedia-importer python scripts/wiki_parser.py data/example_wikipedia-articles.xml; python scripts/wiki_searcher.py "Politic"
